"""create_education_table

Revision ID: 01b758f30467
Revises: de22b839f764
Create Date: 2025-06-05 18:27:38.739476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as postgresql


# revision identifiers, used by Alembic.
revision: str = "01b758f30467"
down_revision: Union[str, None] = "de22b839f764"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "education_theme",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("theme", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("link_to_picture", sa.String(), nullable=True),  # ← Убедитесь что эта строка есть
        sa.Column("tags", postgresql.JSONB(), nullable=True),      # ← И эта строка есть
        sa.Column("related_topics", postgresql.JSONB(), nullable=True),
        sa.PrimaryKeyConstraint("id")
    )

    op.create_table(
        "education_material",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("link_to_picture", sa.String(), nullable=True),
        sa.Column("education_theme_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("subtitle", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["education_theme_id"],
            ["education_theme.id"],
            ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id")
    )

    op.create_table(
        "education_card",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("link_to_picture", sa.String(), nullable=True),
        sa.Column("education_material_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["education_material_id"],
            ["education_material.id"],
            ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id")
    )

    op.create_table(
        "education_progress",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("education_material_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["education_material_id"],
            ["education_material.id"],
            ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "education_material_id", name="uq_user_material")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("education_progress")
    op.drop_table("education_card")
    op.drop_table("education_material")
    op.drop_table("education_theme")
    # ### end Alembic commands ###