"""create exercises tables

Revision ID: b6112f6bbda1
Revises: 75cd51a63f30
Create Date: 2025-10-17 04:58:25.102958

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b6112f6bbda1"
down_revision: Union[str, None] = "75cd51a63f30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_structure",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("picture_link", sa.String(), nullable=False),
        sa.Column("time_to_read", sa.Integer(), nullable=False),
        sa.Column("questions_count", sa.Integer(), nullable=False),
        sa.Column("linked_exercise_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "completed_exercise",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("exercise_structure_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_structure_id"], ["exercise_structure.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exercise_view",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exercise_structure_id", sa.Uuid(), nullable=False),
        sa.Column("view", sa.String(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("picture_link", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_structure_id"], ["exercise_structure.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "field",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("major", sa.Boolean(), nullable=False),
        sa.Column("view", sa.String(length=20), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("placeholder", sa.String(), nullable=True),
        sa.Column("prompt", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("exercise_structure_id", sa.Uuid(), nullable=False),
        sa.Column("exercises", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["exercise_structure_id"], ["exercise_structure.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "filled_field",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("view", sa.String(length=20), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("text", sa.JSON(), nullable=False),
        sa.Column("field_id", sa.Uuid(), nullable=False),
        sa.Column("completed_exercise_id", sa.Uuid(), nullable=False),
        sa.Column("exercises", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["completed_exercise_id"], ["completed_exercise.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["field_id"], ["field.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "variants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("field_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["field_id"], ["field.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("variants")
    op.drop_table("filled_field")
    op.drop_table("field")
    op.drop_table("exercise_view")
    op.drop_table("completed_exercise")
    op.drop_table("exercise_structure")
    # ### end Alembic commands ###
