"""__

Revision ID: 618c6ecc5bd7
Revises: eb8039c1ebac
Create Date: 2025-05-08 10:39:28.823464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "618c6ecc5bd7"
down_revision: Union[str, None] = "eb8039c1ebac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.create_table(
        "inquiry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "review",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        "answer_choice_question_id_fkey", "answer_choice", type_="foreignkey"
    )
    op.drop_column("answer_choice", "question_id")
    op.add_column(
        "question", sa.Column("answer_choice", sa.ARRAY(sa.UUID()), nullable=False)
    )
    op.alter_column("scale", "test_id", existing_type=sa.UUID(), nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("scale", "test_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("question", "answer_choice")

    # 1. Сначала добавляем столбец как nullable
    op.add_column(
        "answer_choice",
        sa.Column("question_id", sa.UUID(), autoincrement=False, nullable=True)  # Изменено на nullable=True
    )

    # 2. Заполняем столбец допустимыми значениями (например, первым вопросом)
    # Получаем первый вопрос из таблицы questions
    op.execute("""
        UPDATE answer_choice 
        SET question_id = (SELECT id FROM question LIMIT 1)
        WHERE question_id IS NULL
    """)

    # 3. Теперь можно установить NOT NULL
    op.alter_column("answer_choice", "question_id", nullable=False)

    # 4. Создаем foreign key
    op.create_foreign_key(
        "answer_choice_question_id_fkey",
        "answer_choice",
        "question",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_table("review")
    op.drop_table("inquiry")
    # ### end Alembic commands ###
