"""Add gamification

Revision ID: 75cd51a63f30
Revises: dbbb151c9b3e
Create Date: 2025-10-06 15:34:57.391459

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "75cd51a63f30"
down_revision: Union[str, None] = "6cbef205be69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_scores',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('score', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_scores_date'), 'user_scores', ['date'], unique=False)
    op.create_index(op.f('ix_user_scores_user_id'), 'user_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_scores_user_id'), table_name='user_scores')
    op.drop_index(op.f('ix_user_scores_date'), table_name='user_scores')
    op.drop_table('user_scores')
    # ### end Alembic commands ###