"""changed_user_model

Revision ID: 1d77765de707
Revises: 8a04d37b34a7
Create Date: 2026-02-23 06:21:10.846925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1d77765de707"
down_revision: Union[str, None] = "8a04d37b34a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.alter_column("users", "city", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "city", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    # ### end Alembic commands ###
