"""add formulation to training_question

Revision ID: e4b5d0d2bb80
Revises: 88a84ff4a4c8
Create Date: 2026-04-08 15:11:56.526708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e4b5d0d2bb80"
down_revision: Union[str, None] = "88a84ff4a4c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_question', sa.Column('formulation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_question', 'formulation')
    # ### end Alembic commands ###